# Volume
bindl =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle 
bindle =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
bindle =, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-

# Brightness
bindle=, XF86MonBrightnessDown, exec, brillo -U 5
bindle=, XF86MonBrightnessUp, exec, brillo -A 5

# Player
binde=, XF86AudioPlay, exec, mpc toggle
binde=, XF86AudioNext, exec, mpc next
binde=, XF86AudioPrev, exec, mpc prev

# Apps: just normal apps
bind = $mainMod,         return,  exec, foot
bind = $mainMod SHIFT,   n,       exec, foot sleep 0.01 && nmtui
bind = $mainMod,         a,       exec, foot -e lf
bind = $mainMod,         n,       exec, foot -e ncmpcpp
bind = $mainMod,         n,       exec, mpd


bind = $mainMod,         e,       exec, emacsclient -c -a emacs
bind = $mainMod,         w,       exec, firefox
bind = $mainMod,         r,       exec, nautilus
bind = $mainMod,         t,       exec, evince
bind = $mainMod SHIFT,   W,       exec, qutebrowser

# Apps: Settings and config
bind = $mainMod CONTROL, V, exec, pavucontrol 
bind = $mainMod CONTROL ALT SHFIT,  Escape, exec, foot -T 'htop' htop

# Actions 
bindr = $mainMod,        b,       exec, pkill .waybar-wrapped || waybar
bindr = $mainMod,        s,       exec, focus.sh
bindr = $mainMod SHIFT,  s,       exec, hyprctl reload
bind  = $mainMod,        Q,       killactive, 
bind  = $mainMod,        M,       exit, 
bind  = $mainMod,        Space,   togglefloating, 
bind  = $mainMod SHIFT,  P,       pseudo, # dwindle
bind  = $mainMod SHIFT,  J,       togglesplit, # dwindle

# Screenshot, Record, Clipboard history
bindr = ,Print,                   exec, grim -g "$(slurp -d)" - | wl-copy -t image/png

# App launcher
bindr = $mainMod,        p,         exec, wofi --show drun
bindr = $mainMod,        Backspace, exec, powermenu

# Swap windows
bind = $mainMod, left, movewindow, l
bind = $mainMod, right, movewindow, r
bind = $mainMod, up, movewindow, u
bind = $mainMod, down, movewindow, d

# Move focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Fullscreen
bind  = $mainMod,        F,            fullscreen,
bind  = $mainMod ALT,    F,            fakefullscreen,

# Switching
bind = $mainMod,         1,             workspace,       1
bind = $mainMod,         2,             workspace,       2
bind = $mainMod,         3,             workspace,       3
bind = $mainMod,         4,             workspace,       4
bind = $mainMod,         5,             workspace,       5
bind = $mainMod,         6,             workspace,       6
bind = $mainMod,         7,             workspace,       7
bind = $mainMod,         8,             workspace,       8
bind = $mainMod,         C,             movetoworkspace, special
bind = $mainMod SHIFT,   C,             togglespecialworkspace

# Move window to workspace  
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8

# Scroll through existing workspaces 
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize 
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind=ALT,R,submap,resize
submap=resize
binde=,right,resizeactive,10 0
binde=,left,resizeactive,-10 0
binde=,up,resizeactive,0 -10
binde=,down,resizeactive,0 10
bind=,escape,submap,reset 
submap=reset
